### ISSUE TITLE
Trabalho Final - 25/11

### ISSUE THREAD

**Issue by fernand0aguilar** [Interacao-Humano-Computador/2019.2-CodeForces#17]
# Trabalho Final 

## Data de entrega
25/11 - (Entrega via Moodle até 23hrs:55min)

***
# Planejamento de Atividades

- [ ] Prototipo de alta fidelidade
- [ ] Teste de Usabilidade [UsabilityHub](https://usabilityhub.com)
- [ ] Refatorar issue #12 
- [ ] Apresentação de acordo com o planejamento do professor

***

Orientações Gerais:

* Planejar a apresentação de forma a demonstrar a dedicação dos membros do grupo em cada módulo ministrado na disciplina.
* Apresentar diretamente na Wiki, para facilitar. Mas, como tem dependência com a internet, procurar trazer alguns "prints" de telas da Wiki, para o caso da internet falhar no momento da apresentação.
* Administrar o uso dos 15 minutos da melhor forma possível, visando demonstrar ao máximo os esforços do grupo ao longo do semestre e na elaboração/especificação dos vários artefatos apresentados nas aulas, com olhar focado em cada módulo.
* Valorizar iniciativas extras, com artefatos que complementam os artefatos cobertos na disciplina, ou mesmo com explicações extras demonstrando reflexões dos membros quanto aos artefatos realizados.

**Comment by fernand0aguilar** [comment]
🐎 pocotó

**Comment by ErickGiffoni** [comment]
Parabéns a todos pelo nosso trabalho !
Fechando a issue.
