### ISSUE TITLE
Postar videos no youtube

### ISSUE THREAD

**Issue by fernand0aguilar** [Interacao-Humano-Computador/2019.2-CodeForces#5]

**Comment by fernand0aguilar** [comment]
Interações protótipo de papel

**Comment by ErickGiffoni** [comment]
**Login** : https://youtu.be/Z2vHAOt55Sc
**Visualizar Contests** : https://youtu.be/vCotdC0vYpI
**Visualizar problemas** : https://youtu.be/Nn_hkbsTcrc
